dataset_name: fern 

near: 1.4
far: 6.0 

split_to_patches: True 
scale: 0.125
split_w: 7 
split_h: 7 
num_samples: 64 

use_hvs: True 
hvs_num_samples: 32 

# batch size will be equal to jax.local_device_count() 
# so setting this to true with only one device will be the same
# as setting to False
use_batch: True 

L_position: 7 

num_epochs: 500000000
init_lr: 5.e-5

ckpt_dir: 'ckpt_lego'
