dataset_name: miso_shop 
data_type: llff
data_path: 'llff_data/miso_shop'

scale: 0.35
mini_batch_size: 4096

num_samples: 64 

use_hvs: True 
hvs_num_samples: 128 

use_batch: True 

L_position: 10 
L_direction: 4

num_epochs: 500000000
init_lr: 1.e-4

ckpt_dir: 'ckpt_gun_dir'
