dataset_name: jen 
data_type: llff
data_path: '123'

scale: 0.35

num_samples: 64 

use_hvs: True 
hvs_num_samples: 128 

# batch size will be equal to jax.local_device_count() 
# so setting this to true with only one device will be the same
# as setting to False
use_batch: True 

L_position: 10 
L_direction: 4

num_epochs: 500000000
init_lr: 1.e-4

ckpt_dir: 'ckpt_beer_dir'
